### ISSUE TITLE
Doesn't work on fresh ubuntu docker (installing from git)

### ISSUE THREAD

**Issue by grzanka** [youPickItUp/qsort_wheel#1]
```
root@203b5ba81ff7:/# pip3 install git+https://github.com/youPickItUp/qsort_wheel.git
Collecting git+https://github.com/youPickItUp/qsort_wheel.git
  Cloning https://github.com/youPickItUp/qsort_wheel.git to /tmp/pip-92ytznf7-build
Installing collected packages: my-qsort
  Running setup.py install for my-qsort ... done
Successfully installed my-qsort-0.1
root@203b5ba81ff7:/# python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import my_qsort
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/my_qsort/__init__.py", line 7, in <module>
    my_qsort = CDLL(lib_path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.6/dist-packages/my_qsort/libmy_qsort.so: cannot open shared object file: No such file or directory
root@203b5ba81ff7:/# ls -al /usr/local/lib/python3.6/dist-packages/my_qsort/
total 16
drwxr-sr-x 3 root staff 4096 Apr 18 14:45 .
drwxrwsr-x 4 root staff 4096 Apr 18 14:45 ..
-rw-r--r-- 1 root staff  652 Apr 18 14:45 __init__.py
```

**Comment by grzanka** [comment]
I confirm it works:

```
root@35545d57f147:/# pip3 install git+https://github.com/youPickItUp/qsort_wheel.git
Collecting git+https://github.com/youPickItUp/qsort_wheel.git
  Cloning https://github.com/youPickItUp/qsort_wheel.git to /tmp/pip-mnmnof0b-build
Installing collected packages: my-qsort
  Running setup.py install for my-qsort ... done
Successfully installed my-qsort-0.1
root@35545d57f147:/# python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import my_qsort
>>> my_qsort.hello()
Hello, World!
>>> t = [3,2,1]
>>> my_qsort.my_sort( t, lambda x,y: x-y)
>>> t
[1, 2, 3]
```
