### ISSUE TITLE
Doesn't work when installing via wheel

### ISSUE THREAD

**Issue by grzanka** [youPickItUp/qsort_wheel#2]
User should be able to install and use package functionality from wheel itself, without need to clone repo. What I did:

1. Cloned repo
2. Made wheel package
3. Move out wheel package outside repo
4. Removed repo directory
5. Installed wheel package
6. Tested if it works

Removing repo was necessary to be sure that only wheel package is enough, not any other file.
It doesn't work:

```
root@203b5ba81ff7:~# git clone https://github.com/youPickItUp/qsort_wheel.git
Cloning into 'qsort_wheel'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 41 (delta 14), reused 37 (delta 12), pack-reused 0
Unpacking objects: 100% (41/41), done.
root@203b5ba81ff7:~# cd qsort_wheel/
root@203b5ba81ff7:~/qsort_wheel# ls
Makefile  README.md  my_qsort  my_qsort.c  my_qsort.h  setup.py  test
root@203b5ba81ff7:~/qsort_wheel# python3 setup.py bdist_wheel
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/my_qsort
copying my_qsort/__init__.py -> build/lib/my_qsort
running build_ext
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/my_qsort-0.1.data
creating build/bdist.linux-x86_64/wheel/my_qsort-0.1.data/purelib
creating build/bdist.linux-x86_64/wheel/my_qsort-0.1.data/purelib/my_qsort
copying build/lib/my_qsort/__init__.py -> build/bdist.linux-x86_64/wheel/my_qsort-0.1.data/purelib/my_qsort
running install_egg_info
running egg_info
creating my_qsort.egg-info
writing my_qsort.egg-info/PKG-INFO
writing dependency_links to my_qsort.egg-info/dependency_links.txt
writing top-level names to my_qsort.egg-info/top_level.txt
writing manifest file 'my_qsort.egg-info/SOURCES.txt'
reading manifest file 'my_qsort.egg-info/SOURCES.txt'
writing manifest file 'my_qsort.egg-info/SOURCES.txt'
Copying my_qsort.egg-info to build/bdist.linux-x86_64/wheel/my_qsort-0.1.data/purelib/my_qsort-0.1.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/my_qsort-0.1.dist-info/WHEEL
creating '/root/qsort_wheel/dist/my_qsort-0.1-cp36-cp36m-linux_x86_64.whl' and adding '.' to it
adding 'my_qsort-0.1.data/purelib/my_qsort/__init__.py'
adding 'my_qsort-0.1.dist-info/DESCRIPTION.rst'
adding 'my_qsort-0.1.dist-info/metadata.json'
adding 'my_qsort-0.1.dist-info/top_level.txt'
adding 'my_qsort-0.1.dist-info/WHEEL'
adding 'my_qsort-0.1.dist-info/METADATA'
adding 'my_qsort-0.1.dist-info/RECORD'
root@203b5ba81ff7:~/qsort_wheel# ls
Makefile  README.md  build  dist  my_qsort  my_qsort.c  my_qsort.egg-info  my_qsort.h  setup.py  test
root@203b5ba81ff7:~/qsort_wheel# mv dist/my_qsort-0.1-cp36-cp36m-linux_x86_64.whl ../
root@203b5ba81ff7:~/qsort_wheel# cd ..
root@203b5ba81ff7:~# rm -rf qsort_wheel/
root@203b5ba81ff7:~# pip3 install my_qsort-0.1-cp36-cp36m-linux_x86_64.whl 
Processing ./my_qsort-0.1-cp36-cp36m-linux_x86_64.whl
Installing collected packages: my-qsort
Successfully installed my-qsort-0.1
root@203b5ba81ff7:~# python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import my_qsort
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/my_qsort/__init__.py", line 7, in <module>
    my_qsort = CDLL(lib_path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.6/dist-packages/my_qsort/libmy_qsort.so: cannot open shared object file: No such file or directory
>>> 
root@
```

**Comment by youPickItUp** [comment]
Repo itself doesn't contain library. It's required to build library before creating wheel.

**Comment by youPickItUp** [comment]
Repo doesn't contain library. It's required to build library before creating wheel. I'm not sure whether this issue is about that, or if it's just a suggestion to add library building to setup.py?
